### ISSUE TITLE
Full stack developer/Working with the backend developer and the frontend developer

### ISSUE THREAD

**Issue by GbadamosiMuibat** [zuri-training/Price-Compare-Team-22#10]
- Partnered with other members, she is working on comments research(how authenticated users can post and red comments, option to delete, edit and add.
- Partnered with the frontend, she is working with other members to create the footer pages

**Comment by Adelakin-Adewumi** [comment]
Done ma

**Comment by Adelakin-Adewumi** [comment]
https://github.com/zuri-training/Price-Compare-Team-22/tree/frontend-Adewumi
https://github.com/zuri-training/Price-Compare-Team-22/blob/main/pricezilla/product/serializers.py
https://github.com/zuri-training/Price-Compare-Team-22/blob/main/pricezilla/product/views.py
https://github.com/zuri-training/Price-Compare-Team-22/blob/main/pricezilla/product/urls.py
