### ISSUE TITLE
Alabi Sunday (Frontend developer)

### ISSUE THREAD

**Issue by GbadamosiMuibat** [zuri-training/Price-Compare-Team-22#24]
- Built the contact page
- Worked on the profile page

**Comment by Capablecode** [comment]
completed

**Comment by Omojiba** [comment]
[Contact and product display done](https://github.com/zuri-training/Price-Compare-Team-22/commit/84155052cdfb73827e28192f4538fdd2c6e2f51d)

**Comment by Capablecode** [comment]
[Profile, Contact and product display done](https://github.com/zuri-training/Price-Compare-Team-22/commit/84155052cdfb73827e28192f4538fdd2c6e2f51d)

**Comment by Capablecode** [comment]
[Profile, Contact and product display done](https://github.com/zuri-training/Price-Compare-Team-22/commit/84155052cdfb73827e28192f4538fdd2c6e2f51d)
