### ISSUE TITLE
Build the price compare page

### ISSUE THREAD

**Issue by Omojiba** [zuri-training/Price-Compare-Team-22#36]

**Comment by debbiejackson14** [comment]
[HTML Price Compare Page Link](https://github.com/zuri-training/Price-Compare-Team-22/blob/Pricezilla-Front-Main/compare.html)
[CSS Link to Price Compare Page](https://github.com/zuri-training/Price-Compare-Team-22/blob/Pricezilla-Front-Main/styles/compare.css)

Currently in progress...

**Comment by debbiejackson14** [comment]
This task was reassigned to @debbiejackson14
