### ISSUE TITLE
Omojiba Toluwase (Frontend)

### ISSUE THREAD

**Issue by GbadamosiMuibat** [zuri-training/Price-Compare-Team-22#5]
- Build the nav bar and footer across all pages
- Built  the homepage
- Made research on how frontend developers uses fetch
- Delegated tasks within the Frontend track
- Presenter on behalf of the team

**Comment by Omojiba** [comment]
[Set up responsive nav and footer across pages](https://github.com/zuri-training/Price-Compare-Team-22/commit/4434895e70bee67aacd0b1326953311943222a5e)
[Built the FAQs page](https://github.com/zuri-training/Price-Compare-Team-22/commit/2cbd30720ace996880061eafb25cb4ed8321081d)
[Built the Sign up page with @GbadamosiMuibat  and @waleboluwatife ](https://github.com/zuri-training/Price-Compare-Team-22/commit/9866b51d8adfd3cc5f001b5befdf50c9706a06f4)
[Built the homepage](https://github.com/zuri-training/Price-Compare-Team-22/commit/f068fe05cde509257fc1b70192e92e641e37080e)
[Delegated tasks within the Frontend](https://docs.google.com/document/d/1y2Jte-xY-QOs3XNNIunRsooRuf1PmxA7WBuJ5T6Hgtk/edit?usp=sharing)
