### ISSUE TITLE
Design mobile view screens lofi

### ISSUE THREAD

**Issue by GbadamosiMuibat** [zuri-training/Price-Compare-Team-22#51]

**Comment by Comfort69** [comment]
I designed the following LOFI mobile view screens:
1. Home Page
[https://www.figma.com/file/QatB0dnXMWYDGu19iBm00N/TEAM-22_PRICE-COMPARE-(Copy)?node-id=1752%3A2600](url)

2. Frequently Asked Question 1
[https://www.figma.com/file/QatB0dnXMWYDGu19iBm00N/TEAM-22_PRICE-COMPARE-(Copy)?node-id=1872%3A2943](url)

3. Frequently Asked Question 2
[https://www.figma.com/file/QatB0dnXMWYDGu19iBm00N/TEAM-22_PRICE-COMPARE-(Copy)?node-id=1888%3A2936](url)

4. Frequently Asked Question 3
[https://www.figma.com/file/QatB0dnXMWYDGu19iBm00N/TEAM-22_PRICE-COMPARE-(Copy)?node-id=1888%3A3015](url)
 
5. Frequently Asked Question 4
[https://www.figma.com/file/QatB0dnXMWYDGu19iBm00N/TEAM-22_PRICE-COMPARE-(Copy)?node-id=1893%3A3028](url)
